      PROGRAM GAUSSIAN_TABLE
      REAL*8 A, B, ANALYTIC_VAL, CURRENT_INTEGRAL
      REAL*8 PREV_INTEGRAL, RUNGE_ERROR, RICHARDSON_CORRECTION
      REAL*8 ERROR, PREV_ERROR, RUNGE_RATIO, CORRECTED_ERROR, H
      INTEGER MAX_DEGREE, N, DEGREE
      EXTERNAL F
      REAL*8 ANALYTIC_VALUE
      REAL*8 GAUSS_QUADRATURE_METHOD

      A = 0.0D0
      B = 1.0D0
      MAX_DEGREE = 10

      PRINT *, 'Degree N Analytic Numeric Error'
      PRINT *, 'Ratio Runge Error Richardson Richardson Error'

      DO DEGREE = 7, MAX_DEGREE
         ANALYTIC_VAL = ANALYTIC_VALUE(A, B, DEGREE)
         PREV_INTEGRAL = 0.0D0
         PREV_ERROR = 0.0D0

         DO N = 1, 2
          CALL CREATE_GRID(A, B, N, H)
          CURRENT_INTEGRAL = GAUSS_QUADRATURE_METHOD(F, A, B, N, DEGREE)

            ERROR = ABS(ANALYTIC_VAL - CURRENT_INTEGRAL)
            IF (N .GT. 1 .AND. PREV_ERROR .NE. 0.0D0) THEN
             RUNGE_RATIO = ERROR / PREV_ERROR
             RUNGE_ERROR = ABS(CURRENT_INTEGRAL - PREV_INTEGRAL) / 255.0D0
             RICHARDSON_CORRECTION = CURRENT_INTEGRAL + RUNGE_ERROR
             CORRECTED_ERROR = ABS(RICHARDSON_CORRECTION - ANALYTIC_VAL)
            ELSE
               RUNGE_RATIO = 0.0D0
               RUNGE_ERROR = 0.0D0
               RICHARDSON_CORRECTION = CURRENT_INTEGRAL
               CORRECTED_ERROR = ERROR
            END IF

C Formatted output
    1 FORMAT(I2, I2, E15.8, E15.8, E15.8, E15.8, E15.8, E15.8, E15.8)
            PRINT 1, DEGREE, N, ANALYTIC_VAL, CURRENT_INTEGRAL,
     &        ERROR, RUNGE_RATIO, RUNGE_ERROR,
     &        RICHARDSON_CORRECTION, CORRECTED_ERROR

            PREV_INTEGRAL = CURRENT_INTEGRAL
            PREV_ERROR = ERROR
         END DO
      END DO
      END

      REAL*8 FUNCTION F(X, DEGREE)
      REAL*8 X
      INTEGER DEGREE
      F = X**DEGREE
      END

      REAL*8 FUNCTION ANALYTIC_VALUE(A, B, DEGREE)
      REAL*8 A, B
      INTEGER DEGREE
      ANALYTIC_VALUE = (B**(DEGREE+1) - A**(DEGREE+1)) / DBLE(DEGREE+1)
      END

      SUBROUTINE CREATE_GRID(A, B, N, H)
      REAL*8 A, B, H
      INTEGER N
      H = (B - A) / DBLE(N)
      END

      REAL*8 FUNCTION GAUSS_QUADRATURE_METHOD(FUNC, A, B, N, DEGREE)
      REAL*8 FUNC, A, B, H, SUM
      INTEGER N, I, DEGREE
      EXTERNAL FUNC
      REAL*8 X(4), W(4)
      REAL*8 GAUSS_SUM
      DATA X /-0.8611363116D0, -0.3399810436D0,
     &  0.3399810436D0, 0.8611363116D0/
      DATA W /0.3478547486D0, 0.6521451549D0,
     &  0.6521451549D0, 0.3478547486D0/

      H = (B - A) / DBLE(N)
      SUM = 0.0D0
      DO I = 1, N
         SUM = SUM + GAUSS_SUM(FUNC, A + 
     & (DBLE(I)-1.0D0)*H, A + DBLE(I)*H, X, W, DEGREE)
      END DO
      GAUSS_QUADRATURE_METHOD = SUM
      END

      REAL*8 FUNCTION GAUSS_SUM(FUNC, A, B, X, W, DEGREE)
      REAL*8 FUNC, A, B
      REAL*8 X(4), W(4)
      INTEGER I, DEGREE
      EXTERNAL FUNC
      REAL*8 VALUE, XI, HALF_WIDTH, MID_POINT
      HALF_WIDTH = (B - A) / 2.0D0
      MID_POINT = (A + B) / 2.0D0
      VALUE = 0.0D0
      DO I = 1, 4
         XI = HALF_WIDTH * X(I) + MID_POINT
         VALUE = VALUE + W(I) * FUNC(XI, DEGREE)
      END DO
      GAUSS_SUM = HALF_WIDTH * VALUE
      END